### ISSUE TITLE
error loading keras model

### ISSUE THREAD

**Issue by superkevinr** [zhwuer/Chinese-Chess#1]
when I try to run the real_time_test.py, I got error like this:
`warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:792)
warning: http://admin:admin@192.168.1.100:8081/ (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:793)
Using TensorFlow backend.
Traceback (most recent call last):
  File "real_time_test.py", line 16, in <module>
    model = load_model('./h5_file/model (1).h5')
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 1367, in from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
KeyError: 0`

**Comment by Earlyao** [comment]
OSError: Unable to open file (unable to open file: name = './h5_file/new_model_v2.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
I think there is no new_model_v2.h5 as the model, so could you share the model?

**Comment by Earlyao** [comment]
> 
> 
> when I try to run the real_time_test.py, I got error like this:
> `warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:792) warning: http://admin:admin@192.168.1.100:8081/ (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:793) Using TensorFlow backend. Traceback (most recent call last): File "real_time_test.py", line 16, in <module> model = load_model('./h5_file/model (1).h5') File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 243, in load_model model = model_from_config(model_config, custom_objects=custom_objects) File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 317, in model_from_config return layer_module.deserialize(config, custom_objects=custom_objects) File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize printable_module_name='layer') File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object list(custom_objects.items()))) File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 1367, in from_config if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge': KeyError: 0`

OSError: Unable to open file (unable to open file: name = './h5_file/new_model_v2.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
I think there is no new_model_v2.h5 as the model, so have you download the h5 model? could you share it with me ?谢谢！
